import "server-only";

export type LeadRecord = {
  site_url: string;
  secteur: string;
  objectif: string;
  budget: string;
  prenom: string;
  email: string;
};

/**
 * Inserts a lead into the NocoDB "leads" table.
 *
 * Requires:
 * - NOCODB_API_URL   base origin of the NocoDB instance (e.g. http://localhost:8080)
 * - NOCODB_API_TOKEN personal/API token, sent as the `xc-token` header
 * - NOCODB_TABLE_ID  internal NocoDB table id for the "leads" table
 *   (generated by NocoDB when the table is created — see scripts/setup-nocodb.mjs)
 *
 * Server-only: never call this from client components, it would leak the token.
 */
export async function createLead(lead: LeadRecord): Promise<void> {
  const baseUrl = process.env.NOCODB_API_URL;
  const token = process.env.NOCODB_API_TOKEN;
  const tableId = process.env.NOCODB_TABLE_ID;

  if (!baseUrl || !token || !tableId) {
    throw new Error(
      "NocoDB is not configured (NOCODB_API_URL / NOCODB_API_TOKEN / NOCODB_TABLE_ID missing)."
    );
  }

  const res = await fetch(`${baseUrl}/api/v2/tables/${tableId}/records`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "xc-token": token,
    },
    body: JSON.stringify({
      site_url: lead.site_url,
      secteur: lead.secteur,
      objectif: lead.objectif,
      budget: lead.budget,
      prenom: lead.prenom,
      email: lead.email,
      statut: "nouveau",
    }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`NocoDB insert failed (${res.status}): ${body}`);
  }
}
